### ISSUE TITLE
Copyright form needs to include 2021 options

### ISSUE THREAD

**Issue by mjslee** [lubaochuan/ccsc-editor#7]
Copyright form needs to include 2021 options (Volume 37) for the dropdown, and also has to update the copyright year in the statement from 2020 to 2021.

**Comment by lubaochuan** [comment]
Thanks for letting me know. I have updated the form with new journal issue numbers and copyright years. You can find your journal issue number from the publication schedule on the home page https://lubaochuan.github.io/ccsc-editor/
